[phases.setup]
nixPkgs = ["dejavu_fonts", "python311", "python311Packages.pip"]

[phases.install]
dependsOn = ["setup"]
cmds = ["python3.11 -m pip install -r requirements.txt"]

[start]
cmd = "python3.11 -m gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300"
